# -*- coding: utf-8 -*-
"""Atividade_Mod1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X2cftYpNbSq03pkIift2ZNkKgRnx3Fg4
"""

'''
Projeto desenvolvido para calcular dois números digitados pelo usuário.
'''

# Apresentação ao usuário (Opcional)
nome_usuario = input('Por favor, digite o seu nome: ') # Solicita para que o usuário digite o seu nome.
print('Olá', nome_usuario, 'seja muito bem-vindo(a)!\n') # Exibe uma mensagem de boas-vindas ao usuário.
print('Agora vamos fazer o cálculo!\n') # Exibe o objetivo do projeto para o usuário.

# Solicitação dos números para calcular
num1 = int(input('Me informe o primeiro número que deseja calcular: ')) # Solicita que o usuário digite o primeiro número para calcular.
num2 = int(input('Me informe o segundo número que deseja calcular: ')) # Solicita que o usuário digite o segundo número para calcular.

# Escolha da operação
opcao_calculo = input('Qual operação você deseja realizar?\nSoma, Subtração, Multiplicação ou Divisão?\n')
# Pergunta para o usuário qual a operação que ele deseja realizar.
# O usuário deverá digitar uma das seguintes opções: Soma, Subtração, Multiplicação ou Divisão.

# Realização da operação e da exibição do resultado.
while True:
# Utilizado o comando while que é indicado para loops baseados em condições.
# Neste caso, repete a solicitação até que o usuário forneça uma operação válida.

  if opcao_calculo.lower() == 'soma':
    # Nessa condição é analisado se a variável opcao_calculo é igual ao dado digitado pelo usuário.
    # O método '.lower()' que está incluído logo após a variável 'opcao_calculo', é utilizado para
    # converter todos os caracteres de uma string para letras minúsculas, sendo bastante útil em situações
    # onde queremos realizar comparações ou manipulações de texto, sem nos preocuparmos
    # com diferenças entre maiúsculas e minúsculas.
    soma = num1 + num2
    # A variável 'soma' armazena o resultado da operação de adição realizada entre
    # os valores das variáveis num1 e num2.
    print('A soma do primeiro número com o segundo número é: ', soma)
    # Exibe para o usuário o resultado da operação de adição.
    break
    # O comando break interrompe o loop while logo assim que a solicitação for atendida.

  elif opcao_calculo.lower() == 'subtração':
    # Se a condição anterior não for atendida, de acordo com a operação escolhida pelo usuário,
    # é acionado o próximo bloco de comando, no caso elif. Se este for válido,
    # o cálculo é executado e o loop é encerrado por meio do comando break.
    subtracao = num1 - num2
    # A variável 'subtracao' armazena o resultado da operação de subtração realizada
    # entre os valores das variáveis num1 e num2.
    print('A subtração do primeiro número com o segundo número é: ', subtracao)
    # Exibe para o usuário o resultado da operação de subtração.
    break

  elif opcao_calculo.lower() == 'multiplicação':
    multiplicacao = num1 * num2
    # A variável 'multiplicacao' armazena o resultado da operação de multiplicação
    # realizada entre os valores das variáveis num1 e num2.
    print('A multiplicação do primeiro número com o segundo número é: ', multiplicacao)
    # Exibe para o usuário o resultado da operação de multiplicação.
    break

  elif opcao_calculo.lower() == 'divisão':
    if num2 != 0:
      # Verifica se o valor da variável num2 é diferente de 0, pois se for igual
      # não será possível dividir e ocorrerá um erro.
      divisao = num1 / num2
      # A variável 'divisao' armazena o resultado da operação de divisão realizada entre
      # os valores das variáveis num1 e num2.
      print('A divisão do primeiro número com o segundo número é: ', divisao)
      # Exibe para o usuário o resultado da operação de divisão.
    else: # O bloco else é utilizado para indicar que esta operação não é possível de ser realizada.
      print('Erro - Não é possível dividir por zero.')
      # Exibe a mensagem para o usuário informando que não é possível dividir o segundo número por zero.
    break

  else: # O bloco else é utilizado caso nenhuma das condições anteriores seja verdadeira.
    opcao_calculo = input('Opção inválida! Escolha qual operação deseja efetuar.\nSoma, Subtração, Multiplicação ou Divisão: ')
    # Ao notar que a opção digitada pelo usuário não é válida, é exibida novamente a mensagem solicitando a opção correta.